services:
  - type: web
    name: shl-recommender-backend
    env: python
    plan: free
    runtime: python
    pythonVersion: "3.10"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: "10000"
    autoDeploy: true
